name: faszen
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_sign_in: ^5.2.1
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  flutter_login_facebook: ^1.9.0
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  pod_player: ^0.2.1
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  showcaseview: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
    
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
