name: faszen
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_sign_in: ^5.2.1
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  flutter_login_facebook: ^1.9.0
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  pod_player: ^0.2.1
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  showcaseview: ^2.0.3
  audioplayers: ^5.2.1
  lottie: ^3.1.2
  drop_cap_text: ^1.1.3
  camerakit_flutter: ^1.0.0
  carousel_slider: ^4.2.1
  o3d: ^3.1.0
  dio: ^5.1.0
  url_launcher: ^6.2.6
  fuzzywuzzy: ^1.1.6
  awesome_notifications: ^0.9.3+1
  table_calendar: ^3.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Animation - 1713787363552.json
    - assets/audio/
    - assets/icons/
    - android/app/src/main/res/mipmap-xxxhdpi/logo.png
    - assets/categories/
    - assets/categories/Tops/
    - assets/categories/Bottoms/
    - assets/categories/Inners/
    - assets/categories/Athleisure/
    - assets/categories/Formals/
    - assets/categories/Casuals/
    - assets/categories/Desi Wear/
    - assets/categories/Western Wear/
    - assets/categories/Street Wear/
    - assets/categories/Luxury Wear/
    - assets/categories/Gift Wear/
    - assets/categories/Footwear/
    - assets/categories/Hats & Beanies/
    - assets/categories/Accessories/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
    
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
